### PR TITLE
change directory to script directory.

### PR DESCRIPTION
**Pull request by ekiyanov**
To make drag n drop to terminal works

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
eh, why would anyone  do it that way?

**Comment by ekiyanov** [comment]
cause it easy and essential

**Comment by ArtSabintsev** [comment]
really? I feel like everything I've ever done involves using a terminal - never dragging and dropping.

**Comment by ekiyanov** [comment]
yes.  cause double click to sh file is not looks natural and typing full
path to directory is not so fast as drag and drop script to already opened
terminal window

**Pull request closed without merging**
